version: '3.4'

services:
  busplan2backend:
    container_name: ASP-Backend
    image: ${DOCKER_REGISTRY-}busplan2backend
    build:
      context: Busplan2 Backend/
      dockerfile: Busplan2 Backend/Dockerfile-back
    environment:
      - ASPNETCORE_URLS=http://+:5000/;https://+:5001
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - db


  react-frontend:
    container_name: React-Frontend
    image: ${DOCKER_REGISTRY-}reactfrontend
    build:
      context: Busplan2 Frontend/
      dockerfile: Dockerfile-front
    ports:
      - "3000:3000"
    volumes: 
      - "/app/node_modules"
      - "./:/app"

  flyway:
      image: flyway/flyway
      container_name: busFlyway
      command: -url=jdbc:mysql://host.docker.internal:3307/busplanDB -user=user -password=root -connectRetries=60 migrate
      volumes:
        - .:/database/flyway/sql/migrations
      depends_on:
        - db

  db:
    image: mysql:latest
    container_name: busDB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'busplanDB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: busPhpmyadmindb
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8080:80
