version: '3.3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'busplanDB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmindb
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8080:80
# docker run --rm -v $PWD/flyway:/flyway/sql flyway/flyway \-url=jdbc:mysql://host.docker.internal:3306/busplanDB \-user=user -password=root \-locations=filesystem:/flyway/sql/migrations \migrate
# docker run --rm -v $PWD/flyway:/flyway/sql flyway/flyway \-url=jdbc:mysql://host.docker.internal:3306/busplanDB \-user=user -password=root \-locations=filesystem:/flyway/sql/testdata \migrate